# Generated by Django 3.0.3 on 2020-03-03 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0005_auto_20200301_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
    ]
